### ISSUE TITLE
[Question] What is chaincode.json

### ISSUE THREAD

**Issue by conanoc** [postfinance/hlfabric-k8scc#11]
Readme.md refers chaincode.json but I'm not sure what it is. I could not find it in example folder.

Another question.  One of the features is "The chaincode must be usable without changes", but it does not conform with the [document](https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html#writing-chaincode-to-run-as-an-external-service) saying the chaincode should be re-written using shim.ChaincodeServer.

**Comment by djboris9** [comment]
Hi @conanoc 

`chaincode.json` is a file that is provided by Hyperledger Fabric to the external launcher in the `run`/launch step and is documented [here](https://hyperledger-fabric.readthedocs.io/en/release-2.1/cc_launcher.html#external-builder-and-launcher-api). We need to extract the key material and the peer address from this file in order to connect to the peer.

For the second question: k8scc doesn't run the chaincode as an external service, but it runs it using an external builder+launcher (see ([cc_launcher](https://hyperledger-fabric.readthedocs.io/en/release-2.1/cc_launcher.html)), therefore no code change is required. Using the [cc_service](https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html) as you've written would require a change in the code and build process and is not the mechanism used by k8scc. Our goal is to be compatible with the native/Docker builder+launcher.

**Comment by conanoc** [comment]
Thanks. I didn't know that I can use the builder+launcher without making the chaincode as an external service. Cool.
